steps:
  - name: 'mcr.microsoft.com/dotnet/sdk:7.0'
    entrypoint: 'dotnet'
    args: ['publish', '-c', 'Release', '-o', 'published']

  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['-m', 'cp', '-r', 'published/wwwroot/*', 'gs://portfolio-project-dev']

options:
  default_logs_bucket_behavior: REGIONAL_USER_OWNED_BUCKET

timeout: 900s
